name: Preview Builds

on:
  push:
    branches:
      - main

jobs:
  preview_android:
    type: build
    params:
      platform: android
      profile: preview
  preview_ios:
    type: build
    params:
      platform: ios
      profile: preview
